---
- name: Create New User
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - include_vars:
        file: group_vars/add_user

    - name: Create CTA group
      group:
        name: cta
        state: present
        gid: 9999
    
    - name: Create a file in sudoers.d and allow CTA group to have passwordless sudo
      lineinfile:
        path: /etc/sudoers.d/cta
        state: present
        mode: 0440
        regexp: '^%cta'
        line: '%cta ALL=(ALL) NOPASSWD:ALL'
        create: yes
        validate: 'visudo -cf %s'

    - name: Create a User
      user:
        name: "{{ user_name }}"
        state: present
        shell: /bin/bash
        group: cta

    - name: Set up authorized keys for a New User
      authorized_key:
        user: "{{ user_name }}"
        state: present
        key: "{{ user_key }}"
      
    - name: Add Comment    
      lineinfile:
        path: /home/{{ user_name }}/.ssh/authorized_keys
        state: present
        insertbefore: BOF
        line: '# Created by Ansible'

...
