---
- name: Create New User
  hosts: all
  gather_facts: no
  become: true
  tasks:
    - include_vars:
        file: group_vars/add_user

    - name: Create CTA group
      raw: groupadd -g 9999 cta
      ignore_errors: yes

    - name: Add cta to sudoers if not exists
      raw: "if [ ! -f /etc/sudoers.d/cta ]; then echo '%cta ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/cta && chmod 440 /etc/sudoers.d/cta; fi"

    - name: Create New User and add to cta group
      raw: useradd -m -g cta {{ user_name }}

    - name: Add ssh user key
      raw: mkdir /home/{{ user_name }}/.ssh;
           echo {{ user_key }} > /home/{{ user_name }}/.ssh/authorized_keys;
           chmod 600 /home/{{ user_name }}/.ssh/authorized_keys;
           chmod 700 /home/{{ user_name }}/.ssh;
           chown -R {{ user_name }}:cta /home/{{ user_name }}/.ssh;

...
