---
- name: Create New User
  hosts: all
  gather_facts: no
  become: true
  tasks:
    - include_vars:
        file: group_vars/users

    - name: Create CTA group
      raw: groupadd -g 9999 cta
      ignore_errors: yes

    - name: Add cta to sudoers if not exists
      raw: "if [ ! -f /etc/sudoers.d/cta ]; then echo '%cta ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/cta && chmod 440 /etc/sudoers.d/cta; fi"

    - name: Create New User and add to cta group
      raw: useradd -m -g cta {{ item.user_name }}
      with_items: "{{ users }}"

    - name: Add ssh user key
      raw: mkdir /home/{{ item.user_name }}/.ssh;
           echo -e "#Created by Ansible raw-sudo-user\n\n{{ item.user_key }}" > /home/{{ item.user_name }}/.ssh/authorized_keys;
           chmod 600 /home/{{ item.user_name }}/.ssh/authorized_keys;
           chmod 700 /home/{{ item.user_name }}/.ssh;
           chown -R {{ item.user_name }}:cta /home/{{ item.user_name }}/.ssh;
      with_items: "{{ users }}"

...
